"""Offline demo data for first-run public examples."""
from __future__ import annotations


def demo_rows() -> list[dict]:
    """Small synthetic result set that exercises the report without API keys."""
    return [
        {
            "topic": "run ai agents locally",
            "query_samples": 3,
            "search_queries": "run ai agents locally; \"run ai agents locally\"; run ai agents locally explained",
            "query_coverage": 1.0,
            "query_consensus": 0.86,
            "cluster_size": 1,
            "cluster_topics": "run ai agents locally",
            "opportunity": 0.63,
            "opportunity_raw": 0.78,
            "opportunity_base": 0.84,
            "confidence": 0.81,
            "demand_gate": 0.93,
            "relevance_gate": 1.0,
            "demand": 0.82,
            "supply_gap": 0.74,
            "cpm_score": 0.68,
            "cpm_mid": 27.0,
            "cpm_source": "demo:AI tools",
            "ad_intent": 0.72,
            "quality_gap": 0.67,
            "volume": 0.78,
            "newcomer_volume": 0.83,
            "p75_volume": 0.88,
            "recent_demand": 0.73,
            "median_vpd": 1800,
            "newcomer_vpd": 2400,
            "newcomer_sample": 4,
            "p75_vpd": 3600,
            "median_views": 160000,
            "recent_success_count": 3,
            "outlier": 0.91,
            "trends": 0.58,
            "comment_demand": 0.42,
            "external_demand": 0.76,
            "competition_gap": 0.72,
            "authority_gap": 0.84,
            "recent_supply_gap": 0.63,
            "age_gap": 0.69,
            "small_channel_gap": 0.75,
            "max_outlier_ratio": 32.4,
            "outlier_unknown_subs": 1,
            "credible_results": 7,
            "raw_credible_results": 10,
            "sampled_results": 30,
            "credible_density": 0.23,
            "title_match_frac": 0.7,
            "recent_credible_results": 3,
            "median_age_days": 420,
            "known_subscriber_results": 6,
            "unknown_subscriber_results": 1,
            "small_channel_frac": 0.75,
            "unique_credible_channels": 7,
            "top_channel_share": 0.14,
            "top3_channel_share": 0.43,
            "n_comments": 120,
            "n_comment_requests": 6,
            "comment_examples": ["Please do one on local setup", "Can you compare agent frameworks?"],
            "trends_status": "demo",
            "trend_slope_score": 0.61,
            "trend_level_score": 0.55,
            "trend_breakout_score": 0.62,
            "trend_rising_score": 0.5,
            "trend_rising_terms": "local ai agents; ollama agents; private ai workflow",
            "external_metric_topic": "local ai agents",
            "external_cpm_score": 0.65,
            "external_cpm": 26.0,
            "external_monthly_searches": 12000,
            "quality_status": "demo",
            "quality_attempted": 3,
            "quality_scored": 3,
            "avg_depth": 0.33,
        },
        {
            "topic": "ai automation for realtors",
            "query_samples": 3,
            "search_queries": "ai automation for realtors; \"ai automation for realtors\"; ai automation for realtors tutorial",
            "query_coverage": 0.67,
            "query_consensus": 0.62,
            "cluster_size": 2,
            "cluster_topics": "ai automation for realtors; real estate ai automation",
            "opportunity": 0.39,
            "opportunity_raw": 0.66,
            "opportunity_base": 0.78,
            "confidence": 0.59,
            "demand_gate": 0.85,
            "relevance_gate": 0.67,
            "demand": 0.74,
            "supply_gap": 0.61,
            "cpm_score": 0.74,
            "cpm_mid": 29.5,
            "cpm_source": "demo:AI tools; real estate intent",
            "ad_intent": 0.8,
            "quality_gap": None,
            "volume": 0.71,
            "newcomer_volume": 0.7,
            "p75_volume": 0.84,
            "recent_demand": 0.62,
            "median_vpd": 1100,
            "newcomer_vpd": 1200,
            "newcomer_sample": 2,
            "p75_vpd": 2700,
            "median_views": 92000,
            "recent_success_count": 2,
            "outlier": 0.64,
            "trends": 0.66,
            "comment_demand": 0.25,
            "external_demand": 0.44,
            "competition_gap": 0.58,
            "authority_gap": 0.42,
            "recent_supply_gap": 0.5,
            "age_gap": 0.6,
            "small_channel_gap": 0.67,
            "max_outlier_ratio": 11.2,
            "outlier_unknown_subs": 0,
            "credible_results": 9,
            "raw_credible_results": 13,
            "sampled_results": 30,
            "credible_density": 0.3,
            "title_match_frac": 0.69,
            "recent_credible_results": 4,
            "median_age_days": 330,
            "known_subscriber_results": 9,
            "unknown_subscriber_results": 0,
            "small_channel_frac": 0.67,
            "unique_credible_channels": 5,
            "top_channel_share": 0.33,
            "top3_channel_share": 0.78,
            "n_comments": 40,
            "n_comment_requests": 2,
            "comment_examples": [],
            "trends_status": "demo",
            "trend_slope_score": 0.72,
            "trend_level_score": 0.54,
            "trend_breakout_score": 0.69,
            "trend_rising_score": 0.65,
            "trend_rising_terms": "real estate ai crm; ai lead follow up",
            "external_metric_topic": "real estate ai automation",
            "external_cpm_score": 0.74,
            "external_cpm": 29.5,
            "external_monthly_searches": 6200,
            "quality_status": "disabled",
            "quality_attempted": 0,
            "quality_scored": 0,
            "avg_depth": None,
        },
    ]
